### ISSUE TITLE
Berks Install does not work with Platformstack > 1.1.2

### ISSUE THREAD

**Issue by mattjbarlow** [rackspace-cookbooks/platformstack#176]
If you create a cookbook that depends only on Platformstack 2.0, if you run a 'berks install' it will not succeed.

Also, I notice that Elkstack has a [pessimistic pin to kibana 1.3](https://github.com/rackspace-cookbooks/elkstack/blob/f2f25791c77e58e7ef6e773c2b476a1da5e7a489/metadata.rb#L16). But, in the berksfile it is actually relying on a cookbook  named 'lwrp_kibana' not the Supermarket community cookbook kibana.

The Supermarket kibana cookbook will not satisfy ~> 1.3.

This is me trying with platformstack 1.5.1. It does the same thing if you pin it to 2.0.0.

```
Unable to satisfy constraints on package kibana due to solution constraint (blah = 0.1.0). Solution constraints that may result in a constraint on kibana: [(blah = 0.1.0) -> (platformstack = 1.5.1) -> (elkstack = {0.1.1,0.3.0,2.1.4}) -> (kibana ~> 1.3)]
Demand that cannot be met: (blah = 0.1.0)
source "https://supermarket.getchef.com"
Artifacts for which there are conflicting dependencies: kibana = 0.1.6 -> [(build-essential >= 0.0.0)]Unable to find a solution for demands: blah (0.1.0)
```

**Comment by martinb3** [comment]
This was actually true before platformstack 2.0 as well. You needed to have Berksfile entries for kibana before 2.0 as well. Please note that the `kibana` cookbook in supermarket is a _different_ cookbook from a different author.

The kibana cookbook we use was recently renamed `kibana_lwrp` (in the last week or so, I think) in order to get it released to supermarket at all, so probably it's just a matter of changing the Berksfile entries to `kibana_lwrp` from `kibana`. I've requested they upload older versions to supermarket under the new name, but I don't think a `1.3` version has been uploaded yet (and `1.4` and greater is for a newly released version of kibana that we haven't tested yet).

**Comment by martinb3** [comment]
https://github.com/rackspace-cookbooks/platformstack/pull/177 removes elkstack from platformstack by default, requiring users to deliberately couple them to use them both. This should help w/ the dependency leak that ends up affecting all downstream cookbooks' Berksfiles.

**Comment by martinb3** [comment]
#177 and https://github.com/rackspace-cookbooks/elkstack/pull/98 should resolve this, as soon as we do a release.

**Comment by martinb3** [comment]
Both platformstack and elkstack have had releases, so this should be all resolved.
